@ProductsManagement_HostAddress = http://localhost:5203

###
POST https://localhost:7264/api/product/product
Authorization: Bearer <Token>
Content-Type: application/json

{
  "name": "Test Product",
  "description": "Sample",
  "price": 99.99,
  "categoryId": 1,
  "imageUrl": "http://image.jpg"
}
###

POST {{ProductsManagement_HostAddress}}/api/account/login
Content-Type: application/json
{
  "email": "admin@gmail.com",
  "password": "admin123"
}